### ISSUE TITLE
CircleCi2.0でBrowserテストを実施できるようにする

### ISSUE THREAD

**Issue by yasuhitotanaka** [yasuhitotanaka/Jandi#2]
CircleCI上でDuskがうまく動かないので、あとで確認する

![image](https://user-images.githubusercontent.com/29055447/48815364-db875680-ed70-11e8-8afd-b8d99870b0fb.png)

.circleci/config.yml

```yml
      # - run:
      #    name: install dusk
      #    command: php artisan dusk:install

      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: vendor/bin/phpunit

      # - run:
      #    name: Test 2 - Run Laravel Desk for Browser Testing
      #    command: php artisan dusk
```
